### ISSUE TITLE
Vive pro 2 - eyes not joined

### ISSUE THREAD

**Issue by ossafe** [ProjectMimer/xivr#3]
Starting on the Vive Pro 2 (3090 / 12900K / 64GB) the eyes are not joined into one contiguous screen. So I see 2 screens, one in left eye and one in right eye. There doesn't seem to be a way to adjust the horizontal alignment to bring the two separate images together into one image.  2D VR preview shows the screen properly as expected.

**Comment by evandde** [comment]
Exactly same problem with Meta Quest Pro (3070ti). I see a screen on my left eye and on right eye seperately.
The both are same image, but not aligned.
It looks like "3D with side-by-side video".

**Comment by ossafe** [comment]
The newly documented 

/xivr swapeyes 
/xivr swapeyesui 

commands fix the problem for me.
